TYPO3:
  Flow:
    security:
      enable: TRUE
      authentication:
        authenticationStrategy: oneToken
        providers:
          Test1Provider:
            provider: 'DERHANSEN\AuthTest\Security\Authentication\Provider\Test1Provider'
            providerOptions:
              password: test1234
              authenticateRoles: ['DERHANSEN.AuthTest:Authenticated']
            entryPoint: 'WebRedirect'
            entryPointOptions:
              uri: 'derhansen.authtest/login'